requires 'Tcl' => '1.02';
requires 'AnyEvent::IRC::Client';
requires 'Time::Out';
requires 'Moose';
requires 'AnyEvent::Socket';
requires 'MooseX::Callbacks';
requires 'Config::JFDI';
requires 'Module::Pluggable::Object';
requires 'AnyEvent::Twitter';
requires 'LWP::Authen::OAuth2';
requires 'AnyEvent::WebSocket::Client';
requires 'Twiggy::Server';
requires 'Plack';
requires 'JSON';
